name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-03-30"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "fdrf"
database_id = "0f991f74-1573-4dce-a2a7-93bfcfae1780"
